# Generated by Django 5.1.5 on 2025-01-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0002_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='crushing_date',
            field=models.DateField(blank=True, help_text='Date of crushing/pressing', null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='juice_yield',
            field=models.FloatField(blank=True, help_text='Juice yield in liters', null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='pressing_notes',
            field=models.TextField(blank=True, help_text='Notes about the crushing/pressing process', null=True),
        ),
    ]
