# Generated by Django 5.1.5 on 2025-01-27 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0003_harvest_crushing_date_harvest_juice_yield_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the cellar', max_length=100)),
                ('location', models.CharField(help_text='Location of the cellar', max_length=200)),
                ('capacity', models.FloatField(help_text='Total capacity in liters')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the cellar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or identifier of the tank', max_length=100)),
                ('tank_type', models.CharField(choices=[('stainless_steel', 'Stainless Steel'), ('oak_barrel', 'Oak Barrel'), ('concrete', 'Concrete'), ('fiberglass', 'Fiberglass')], help_text='Type of tank', max_length=50)),
                ('capacity', models.FloatField(help_text='Capacity in liters')),
                ('current_volume', models.FloatField(default=0, help_text='Current volume in liters')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the tank', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='vineyards.cellar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
