# Generated by Django 5.1.5 on 2025-01-28 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0005_crushedjuiceallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='grape_variety',
            field=models.CharField(choices=[('cabernet_sauvignon', 'Cabernet Sauvignon'), ('grasevina', 'Graševina'), ('merlot', 'Merlot'), ('pinot_noir', 'Pinot Noir'), ('chardonnay', 'Chardonnay'), ('sauvignon_blanc', 'Sauvignon Blanc'), ('syrah', 'Syrah'), ('zinfandel', 'Zinfandel'), ('riesling', 'Riesling'), ('tempranillo', 'Tempranillo'), ('sangiovese', 'Sangiovese'), ('malbec', 'Malbec'), ('grenache', 'Grenache'), ('nebbiolo', 'Nebbiolo'), ('pinot_grigio', 'Pinot Grigio'), ('viognier', 'Viognier'), ('cabernet_franc', 'Cabernet Franc'), ('barbera', 'Barbera'), ('moscato', 'Moscato'), ('shiraz', 'Shiraz'), ('carmenere', 'Carmenere')], max_length=255),
        ),
        migrations.CreateModel(
            name='TankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('allocation', 'Allocation from Harvest'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('date', models.DateField()),
                ('volume', models.FloatField(help_text='Volume change in liters (positive for in, negative for out)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='vineyards.tank')),
                ('harvest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vineyards.harvest')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='vineyards.tank')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vineyards.tank')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
