# Generated by Django 5.1.5 on 2025-01-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0006_alter_vineyard_grape_variety_tankhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vineyard',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vineyard',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='vineyard',
            name='contact_phone',
        ),
    ]
