# Generated by Django 5.1.5 on 2025-01-28 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0007_remove_vineyard_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='cellar',
        ),
        migrations.RemoveField(
            model_name='vineyard',
            name='company',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company',
        ),
        migrations.RemoveField(
            model_name='crushedjuiceallocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='crushedjuiceallocation',
            name='harvest',
        ),
        migrations.RemoveField(
            model_name='crushedjuiceallocation',
            name='tank',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='vineyard',
        ),
        migrations.RemoveField(
            model_name='tankhistory',
            name='harvest',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tankhistory',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tankhistory',
            name='source',
        ),
        migrations.RemoveField(
            model_name='tankhistory',
            name='tank',
        ),
        migrations.RemoveField(
            model_name='tankhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vineyard',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ibk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IBK'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mibpg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MIBPG'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='oib',
            field=models.CharField(max_length=11, unique=True, verbose_name='OIB'),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='arkod_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ARKOD ID'),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='cadastral_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='cadastral_parcel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='grape_variety',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='ownership_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('supplied', 'Supplied')], default='owned', max_length=10),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='planting_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='size',
            field=models.DecimalField(decimal_places=2, help_text='Size in hectares', max_digits=10),
        ),
        migrations.DeleteModel(
            name='Cellar',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CrushedJuiceAllocation',
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
        migrations.DeleteModel(
            name='Tank',
        ),
        migrations.DeleteModel(
            name='TankHistory',
        ),
    ]
