# Generated by Django 5.1.5 on 2025-01-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0008_remove_tank_cellar_remove_vineyard_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vineyard',
            options={'ordering': ['name'], 'verbose_name': 'Vineyard', 'verbose_name_plural': 'Vineyards'},
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='grape_variety',
            field=models.CharField(choices=[('plavac_mali', 'Plavac Mali'), ('teran', 'Teran'), ('babic', 'Babić'), ('crljenak', 'Crljenak Kaštelanski (Zinfandel)'), ('merlot', 'Merlot'), ('cabernet_sauvignon', 'Cabernet Sauvignon'), ('syrah', 'Syrah'), ('plavina', 'Plavina'), ('lasina', 'Lasina'), ('marsellan', 'Marsellan'), ('malvazija', 'Malvazija Istarska'), ('grasevina', 'Graševina'), ('posip', 'Pošip'), ('debit', 'Debit'), ('marastina', 'Maraština'), ('kraljevina', 'Kraljevina'), ('skrlet', 'Škrlet'), ('chardonnay', 'Chardonnay'), ('sauvignon_blanc', 'Sauvignon Blanc'), ('muskat', 'Muškat'), ('vugava', 'Vugava'), ('zlahtina', 'Žlahtina'), ('malvasia_dubrovacka', 'Malvasija Dubrovačka'), ('other', 'Other (specify in notes)')], max_length=50),
        ),
    ]
