# Generated by Django 5.1.5 on 2025-01-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0009_alter_vineyard_options_alter_vineyard_grape_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='grape_variety',
            field=models.CharField(choices=[('merlot', 'Merlot'), ('cabernet_sauvignon', 'Cabernet Sauvignon'), ('syrah', 'Syrah'), ('cabernet_franc', 'Cabernet Franc'), ('pinot_noir', 'Pinot Noir'), ('zweigelt', 'Zweigelt'), ('grasevina', 'Graševina'), ('chardonnay', 'Chardonnay'), ('sauvignon_blanc', 'Sauvignon Blanc'), ('muskat', 'Muškat'), ('pinot_bijeli', 'Pinot Bijeli'), ('pinot_sivi', 'Pinot Sivi'), ('rajnski_rizling', 'Rajnski Rizling'), ('other', 'Other (specify in notes)')], max_length=50),
        ),
    ]
