# Generated by Django 5.1.5 on 2025-02-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0010_alter_vineyard_grape_variety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='arkod_id',
            field=models.CharField(blank=True, help_text='ARKOD identification number', max_length=20),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='cadastral_county',
            field=models.CharField(blank=True, help_text='Cadastral county where the vineyard is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='cadastral_parcel',
            field=models.CharField(blank=True, help_text='Official cadastral parcel number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vineyards_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='grape_variety',
            field=models.CharField(choices=[('merlot', 'Merlot'), ('cabernet_sauvignon', 'Cabernet Sauvignon'), ('syrah', 'Syrah'), ('cabernet_franc', 'Cabernet Franc'), ('pinot_noir', 'Pinot Noir'), ('zweigelt', 'Zweigelt'), ('grasevina', 'Graševina'), ('chardonnay', 'Chardonnay'), ('sauvignon_blanc', 'Sauvignon Blanc'), ('muskat', 'Muškat'), ('pinot_bijeli', 'Pinot Bijeli'), ('pinot_sivi', 'Pinot Sivi'), ('rajnski_rizling', 'Rajnski Rizling'), ('other', 'Other (specify in notes)')], help_text='Primary grape variety grown', max_length=50),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='location',
            field=models.CharField(help_text='Physical location of the vineyard', max_length=200),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='name',
            field=models.CharField(help_text='Name of the vineyard', max_length=100),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the vineyard'),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='ownership_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('supplied', 'Supplied')], help_text='Whether the vineyard is owned or supplied', max_length=10),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='planting_year',
            field=models.IntegerField(blank=True, help_text='Year when the vineyard was planted', null=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier for this vineyard (if supplied)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vineyards', to='vineyards.supplier'),
        ),
    ]
