# Generated by Django 5.1.5 on 2025-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0011_alter_vineyard_arkod_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='cadastral_county',
            field=models.CharField(blank=True, help_text='Cadastral county where the vineyard is located', max_length=100, null=True),
        ),
    ]
