# Generated by Django 5.1.5 on 2025-02-10 20:35

from django.db import migrations


def load_initial_grape_varieties(apps, schema_editor):
    """Load initial grape variety data."""
    GrapeVariety = apps.get_model('vineyards', 'GrapeVariety')
    Organization = apps.get_model('organizations', 'Organization')
    
    # Get all organizations
    organizations = Organization.objects.all()
    
    # Initial varieties focusing on the most common ones
    varieties = [
        # Red varieties (CV)
        ('CV036', 'Cabernet Sauvignon', 'red', 'cabernet_sauvignon'),
        ('CV115', 'Merlot', 'red', 'merlot'),
        ('CV200', 'Syrah', 'red', 'syrah'),
        ('CV035', 'Cabernet Franc', 'red', 'cabernet_franc'),
        ('CV065', 'Frankovka', 'red', 'frankovka'),
        ('CV012', 'Babić', 'red', 'babic'),
        ('CV024', 'Blatina', 'red', 'blatina'),
        ('CV054', 'Dobričić', 'red', 'dobricic'),
        ('CV097', 'Lasina', 'red', 'lasina'),
        
        # White varieties (BV)
        ('BV073', 'Graševina', 'white', 'grasevina'),
        ('BV041', 'Chardonnay', 'white', 'chardonnay'),
        ('BV126', 'Muškat bijeli', 'white', 'muskat'),
        ('BV109', 'Malvazija istarska', 'white', 'malvazija_istarska'),
        ('BV108', 'Malvasija dubrovačka bijela', 'white', 'malvasija_dubrovacka'),
        ('BV076', 'Grk', 'white', 'grk'),
        ('BV052', 'Debit', 'white', 'debit'),
        ('BV091', 'Kraljevina', 'white', 'kraljevina'),
        ('BV202', 'Škrlet', 'white', 'skrlet'),
    ]
    
    # Create varieties for each organization
    for org in organizations:
        for code, name, type_, system_code in varieties:
            GrapeVariety.objects.get_or_create(
                organization=org,
                code=code,
                defaults={
                    'name': name,
                    'type': type_,
                    'system_code': system_code
                }
            )

def remove_grape_varieties(apps, schema_editor):
    """Remove all grape varieties."""
    GrapeVariety = apps.get_model('vineyards', 'GrapeVariety')
    GrapeVariety.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0017_grapevariety'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            load_initial_grape_varieties,
            remove_grape_varieties
        ),
    ]
