# Generated by Django 5.1.5 on 2025-01-28 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the cellar', max_length=100)),
                ('location', models.CharField(help_text='Location of the cellar', max_length=200)),
                ('capacity', models.FloatField(help_text='Total capacity in liters')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the cellar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cellar',
                'verbose_name_plural': 'Cellars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or identifier of the tank', max_length=100)),
                ('tank_type', models.CharField(choices=[('stainless_steel', 'Stainless Steel'), ('oak_barrel', 'Oak Barrel'), ('concrete', 'Concrete'), ('fiberglass', 'Fiberglass')], help_text='Type of tank', max_length=50)),
                ('capacity', models.FloatField(help_text='Capacity in liters')),
                ('current_volume', models.FloatField(default=0, help_text='Current volume in liters')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the tank', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='cellars.cellar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tank',
                'verbose_name_plural': 'Tanks',
                'ordering': ['cellar', 'name'],
                'unique_together': {('cellar', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CrushedJuiceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_volume', models.FloatField(help_text='Volume allocated to this tank in liters')),
                ('allocation_date', models.DateField(help_text='Date of allocation')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the allocation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='harvests.harvest')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='cellars.tank')),
            ],
            options={
                'verbose_name': 'Crushed Juice Allocation',
                'verbose_name_plural': 'Crushed Juice Allocations',
                'ordering': ['-allocation_date'],
            },
        ),
        migrations.CreateModel(
            name='TankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('allocation', 'Allocation from Harvest'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('date', models.DateField()),
                ('volume', models.FloatField(help_text='Volume change in liters (positive for in, negative for out)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='cellars.tank')),
                ('harvest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvests.harvest')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='cellars.tank')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cellars.tank')),
            ],
            options={
                'verbose_name': 'Tank History',
                'verbose_name_plural': 'Tank Histories',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
