# Generated by Django 5.1.5 on 2025-01-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0001_initial'),
        ('harvests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crushedjuiceallocation',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crushed_juice_allocations', to='harvests.harvest'),
        ),
        migrations.AlterField(
            model_name='crushedjuiceallocation',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crushed_juice_allocations', to='cellars.tank'),
        ),
    ]
