# Generated by Django 5.1.5 on 2025-01-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0003_create_initial_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankhistory',
            name='operation_type',
            field=models.CharField(choices=[('allocation', 'Allocation from Harvest'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('bottling', 'Bottling')], max_length=20),
        ),
    ]
