# Generated by Django 5.1.5 on 2025-02-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0004_alter_tankhistory_operation_type'),
        ('harvests', '0004_harvest_price_per_kg_harvest_vat_per_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the cellar was created'),
        ),
        migrations.AlterField(
            model_name='cellar',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the cellar', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cellar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the cellar was last updated'),
        ),
        migrations.AlterField(
            model_name='crushedjuiceallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the allocation was created'),
        ),
        migrations.AlterField(
            model_name='crushedjuiceallocation',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the allocation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crushedjuiceallocation',
            name='harvest',
            field=models.ForeignKey(help_text='Harvest that the juice came from', on_delete=django.db.models.deletion.CASCADE, related_name='crushed_juice_allocations', to='harvests.harvest'),
        ),
        migrations.AlterField(
            model_name='crushedjuiceallocation',
            name='tank',
            field=models.ForeignKey(help_text='Tank that the juice was allocated to', on_delete=django.db.models.deletion.CASCADE, related_name='crushed_juice_allocations', to='cellars.tank'),
        ),
        migrations.AlterField(
            model_name='crushedjuiceallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the allocation was last updated'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='cellar',
            field=models.ForeignKey(help_text='Cellar that the tank belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='cellars.cellar'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the tank was created'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the tank', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the tank was last updated'),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the history entry was created'),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the history entry', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='date',
            field=models.DateField(help_text='Date of the operation'),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Destination tank for transfer operations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='cellars.tank'),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='harvest',
            field=models.ForeignKey(blank=True, help_text='Harvest associated with the operation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvests.harvest'),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the operation', null=True),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='operation_type',
            field=models.CharField(choices=[('allocation', 'Allocation from Harvest'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('bottling', 'Bottling')], help_text='Type of operation', max_length=20),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Source tank for transfer operations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='cellars.tank'),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='tank',
            field=models.ForeignKey(help_text='Tank that the history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cellars.tank'),
        ),
    ]
