# Generated by Django 5.1.5 on 2025-02-01 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0005_alter_cellar_created_at_alter_cellar_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the tank', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tank',
            name='tank_type',
            field=models.CharField(choices=[('stainless_steel', 'Stainless Steel'), ('oak_barrel', 'Oak Barrel'), ('concrete', 'Concrete'), ('fiberglass', 'Fiberglass')], default='stainless_steel', help_text='Type of tank', max_length=20),
        ),
    ]
