# Generated by Django 5.1.5 on 2025-02-01 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0006_alter_tank_created_by_alter_tank_tank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellar',
            name='capacity',
            field=models.DecimalField(decimal_places=2, help_text='Total capacity in liters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crushedjuiceallocation',
            name='allocated_volume',
            field=models.DecimalField(decimal_places=2, help_text='Volume allocated to this tank in liters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='capacity',
            field=models.DecimalField(decimal_places=2, help_text='Capacity in liters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='current_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current volume in liters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tankhistory',
            name='volume',
            field=models.DecimalField(decimal_places=2, help_text='Volume change in liters (positive for in, negative for out)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
