# Generated by Django 5.1.5 on 2025-02-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0007_alter_cellar_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellar',
            name='capacity',
        ),
    ]
