# Generated by Django 5.1.5 on 2025-01-28 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0002_alter_crushedjuiceallocation_harvest_and_more'),
        ('packaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottling_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(help_text='Number of bottles')),
                ('status', models.CharField(choices=[('unfinished', 'Unfinished'), ('finished', 'Finished')], default='unfinished', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottlings', to='packaging.bottle')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bottlings', to='packaging.box')),
                ('closure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bottlings', to='packaging.closure')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottlings_created', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bottlings', to='packaging.label')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottlings', to='cellars.tank')),
            ],
            options={
                'verbose_name': 'Bottling',
                'verbose_name_plural': 'Bottlings',
                'ordering': ['-bottling_date'],
            },
        ),
    ]
