# Generated by Django 5.1.5 on 2025-02-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_bottling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier of the bottles', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier of the boxes', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier of the closures', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier of the labels', max_length=255, null=True),
        ),
    ]
