# Generated by Django 5.1.5 on 2025-01-28 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vineyards', '0008_remove_tank_cellar_remove_vineyard_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField(help_text='Quantity in kilograms')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crushing_date', models.DateField(blank=True, help_text='Date of crushing/pressing', null=True)),
                ('juice_yield', models.FloatField(blank=True, help_text='Juice yield in liters', null=True)),
                ('pressing_notes', models.TextField(blank=True, help_text='Notes about the crushing/pressing process', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vineyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='vineyards.vineyard')),
            ],
            options={
                'verbose_name': 'Harvest',
                'verbose_name_plural': 'Harvests',
                'ordering': ['-date'],
            },
        ),
    ]
