# Generated by Django 5.1.5 on 2025-01-28 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0002_alter_crushedjuiceallocation_harvest_and_more'),
        ('harvests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_volume', models.FloatField(help_text='Volume in liters')),
                ('allocation_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_allocations', to='harvests.harvest')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_allocations', to='cellars.tank')),
            ],
            options={
                'verbose_name': 'Harvest Allocation',
                'verbose_name_plural': 'Harvest Allocations',
                'ordering': ['-allocation_date'],
            },
        ),
    ]
