# Generated by Django 5.1.5 on 2025-01-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0002_harvestallocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvestallocation',
            options={'ordering': ['-allocation_date', '-created_at'], 'verbose_name': 'Harvest Allocation', 'verbose_name_plural': 'Harvest Allocations'},
        ),
        migrations.RemoveField(
            model_name='harvestallocation',
            name='updated_at',
        ),
    ]
