# Generated by Django 5.1.5 on 2025-01-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0003_alter_harvestallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per kilogram', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='vat_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT amount per kilogram', max_digits=10, null=True),
        ),
    ]
