# Generated by Django 5.1.5 on 2025-02-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0005_alter_cellar_created_at_alter_cellar_created_by_and_more'),
        ('harvests', '0004_harvest_price_per_kg_harvest_vat_per_kg'),
        ('vineyards', '0011_alter_vineyard_arkod_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Harvest', 'verbose_name_plural': 'Harvests'},
        ),
        migrations.AlterField(
            model_name='harvest',
            name='date',
            field=models.DateField(help_text='Date of harvest'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the harvest', null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.FloatField(help_text='Quantity of grapes harvested in kilograms'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='vat_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='VAT percentage (e.g., 25 for 25%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='vineyard',
            field=models.ForeignKey(help_text='Vineyard where grapes were harvested', on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='vineyards.vineyard'),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='allocated_volume',
            field=models.FloatField(help_text='Volume of juice allocated in liters'),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='allocation_date',
            field=models.DateField(help_text='When the allocation was made'),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='harvest',
            field=models.ForeignKey(help_text='Harvest being allocated', on_delete=django.db.models.deletion.CASCADE, related_name='harvest_allocations', to='harvests.harvest'),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the allocation', null=True),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='tank',
            field=models.ForeignKey(help_text='Tank receiving the juice', on_delete=django.db.models.deletion.CASCADE, related_name='harvest_allocations', to='cellars.tank'),
        ),
    ]
