# Generated by Django 5.1.5 on 2025-02-01 19:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellars', '0007_alter_cellar_capacity_and_more'),
        ('harvests', '0006_harvest_updated_by_harvestallocation_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestallocation',
            name='notes',
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='allocated_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='allocation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='harvests.harvest'),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_allocations', to='cellars.tank'),
        ),
        migrations.AlterField(
            model_name='harvestallocation',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_allocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
