# Generated by Django 5.1.5 on 2025-02-01 19:24

import django.core.validators
from django.db import migrations, models
import django.core.validators
from decimal import Decimal

def convert_juice_yield_to_volume(apps, schema_editor):
    Harvest = apps.get_model('harvests', 'Harvest')
    for harvest in Harvest.objects.all():
        if harvest.juice_yield is not None and harvest.quantity is not None:
            # Convert from percentage to volume
            harvest.juice_yield = Decimal(str(harvest.quantity)) * Decimal(str(harvest.juice_yield))
            harvest.save(update_fields=['juice_yield'])

def convert_juice_yield_to_percentage(apps, schema_editor):
    Harvest = apps.get_model('harvests', 'Harvest')
    for harvest in Harvest.objects.all():
        if harvest.juice_yield is not None and harvest.quantity is not None and harvest.quantity > 0:
            # Convert back to percentage
            harvest.juice_yield = Decimal(str(harvest.juice_yield)) / Decimal(str(harvest.quantity))
            harvest.save(update_fields=['juice_yield'])

class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0007_remove_harvestallocation_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='juice_yield',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Volume of juice obtained in liters',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.RunPython(
            convert_juice_yield_to_volume,
            convert_juice_yield_to_percentage
        ),
    ]
