# Generated by Django 5.1.5 on 2025-02-01 19:30

from django.db import migrations
from decimal import Decimal

def fix_juice_yield_values(apps, schema_editor):
    Harvest = apps.get_model('harvests', 'Harvest')
    for harvest in Harvest.objects.all():
        if harvest.juice_yield is not None:
            # The current value is quantity * percentage * quantity
            # We want just quantity * percentage
            # So divide by quantity once
            harvest.juice_yield = Decimal(str(harvest.juice_yield)) / Decimal(str(harvest.quantity))
            harvest.save(update_fields=['juice_yield'])

def reverse_juice_yield_values(apps, schema_editor):
    Harvest = apps.get_model('harvests', 'Harvest')
    for harvest in Harvest.objects.all():
        if harvest.juice_yield is not None and harvest.quantity is not None:
            # Multiply by quantity to reverse the operation
            harvest.juice_yield = Decimal(str(harvest.juice_yield)) * Decimal(str(harvest.quantity))
            harvest.save(update_fields=['juice_yield'])

class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0008_alter_harvest_juice_yield'),
    ]

    operations = [
        migrations.RunPython(
            fix_juice_yield_values,
            reverse_juice_yield_values
        ),
    ]
