# Generated by Django 5.1.5 on 2025-02-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0009_fix_juice_yield_values'),
        ('organizations', '0001_initial'),
        ('vineyards', '0015_supplier_organization_supplier_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='harvestallocation',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='vineyard',
            field=models.ForeignKey(help_text='Vineyard where grapes were harvested', on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='vineyards.vineyard'),
        ),
    ]
